import { Chat } from "@/components/Chat";

export default function Page() {
  return (
    <>
      <header className="topbar">
        <div className="topbar-inner">
          <span className="brand-group">
            <a
              href="https://axiom-foundation.org"
              target="_blank"
              rel="noreferrer"
              className="brand-link"
              aria-label="Axiom Foundation"
            >
              <img
                src="/axiom-foundation.svg"
                alt="Axiom Foundation"
                className="brand-axiom"
              />
            </a>
            <span className="brand-divider" aria-hidden="true" />
            <span className="brand-product">FinBot</span>
          </span>
        </div>
      </header>

      <main style={{ maxWidth: 980, margin: "0 auto", padding: "56px 20px 80px" }}>
        <div className="page-intro" style={{ marginBottom: 36 }}>
          <h1>
            A benefits assistant powered by the{" "}
            <em>Axiom rules engine</em>.
          </h1>
          <p>
            Every dollar and eligibility verdict is computed against the
            SNAP rulebooks for Colorado, California, and New York — not generated by the language model on top.
          </p>
        </div>

        <Chat />
      </main>
    </>
  );
}
