"use client";

import Link from "next/link";

import { Chat } from "@/components/Chat";

export function FinBotPage() {
  return (
    <>
      <header className="topbar">
        <div className="topbar-inner">
          <span className="brand-group">
            <a
              href="https://axiom-foundation.org"
              target="_blank"
              rel="noreferrer"
              className="brand-link"
              aria-label="Axiom Foundation"
            >
              <img
                src="/gallery/chatbot/axiom-foundation.svg"
                alt="Axiom Foundation"
                className="brand-axiom"
              />
            </a>
          </span>
          <Link
            href="/programs"
            className="mono"
            style={{
              marginLeft: "auto",
              fontSize: 13,
              color: "#374151",
              textDecoration: "underline",
              textUnderlineOffset: 3,
            }}
          >
            Programs
          </Link>
        </div>
      </header>

      <main style={{ maxWidth: 980, margin: "0 auto", padding: "56px 20px 80px" }}>
        <div className="page-intro" style={{ marginBottom: 36 }}>
          <h1>
            A benefits assistant powered by the <em>Axiom rules engine</em>.
          </h1>
          <p>
            Every dollar and eligibility verdict is computed against certified
            rulespec-us programs — SNAP, TANF, and income tax across dozens of
            jurisdictions — not generated by the language model on top.
          </p>
        </div>

        <Chat />
      </main>
    </>
  );
}
