"use client";

import Link from "next/link";

import { Chat } from "@/components/Chat";

export function FinBotPage() {
  return (
    <>
      <header className="topbar">
        <div className="topbar-inner">
          <span className="brand-group">
            <a
              href="https://axiom-foundation.org"
              target="_blank"
              rel="noreferrer"
              className="brand-link"
              aria-label="Axiom Foundation"
            >
              <img
                src="/chatbot/axiom-foundation.svg"
                alt="Axiom Foundation"
                className="brand-axiom"
              />
            </a>
          </span>
          <span
            className="mono"
            style={{
              marginLeft: "auto",
              display: "flex",
              alignItems: "center",
              gap: 16,
            }}
          >
            <a
              href="https://axiom-foundation.org/demos"
              target="_blank"
              rel="noreferrer"
              style={{
                fontSize: 13,
                color: "#374151",
                textDecoration: "underline",
                textUnderlineOffset: 3,
              }}
            >
              All demos
            </a>
            <Link
              href="/programs"
              style={{
                fontSize: 13,
                color: "#374151",
                textDecoration: "underline",
                textUnderlineOffset: 3,
              }}
            >
              Programs
            </Link>
          </span>
        </div>
      </header>

      <main style={{ maxWidth: 980, margin: "0 auto", padding: "56px 20px 80px" }}>
        <div className="page-intro" style={{ marginBottom: 36 }}>
          <h1>
            A benefits assistant powered by the <em>Axiom rules engine</em>.
          </h1>
          <p>
            Every dollar and eligibility verdict is computed against certified
            rulespec-us programs — SNAP, TANF, and income tax across dozens of
            jurisdictions — not generated by the language model on top.
          </p>
        </div>

        <Chat />
      </main>
    </>
  );
}
